What you have to know about yourself and your loved ones. About people:
- your personality is :fluid. It changes from moment to moment, day to day, minute to minute. It changes when you walk into a new room or talk to a new person. It can change huge with a change of diet or a big life event. You may not notice it.
- you have a subconscious. you are not aware of 90% of what is going on inside your mind and body. your brain is concocting plans, solving puzzles, making opinions, sorting our memories, in real time right under your nose.  your  you take in smells, sounds, and process them without realizing it. you have emotions sloshing around that ebb and flow and make you happy or sad for reasons you don't understand.
- you're an excellent storyteller. you don't know the cause of a feeling, you will come up with a story. but just because you have a convincing story doesn't mean it's correct
- you are not fully in control of yourself
* you can't fully control your thoughts. go ahead and try. it's not easy. you can't just decide to calm down when you're mad. you can't decide to be happy. you can't just act perfect all the time
* you're not in control of your emotions. if you're miserable, you can't just fool people into thinking you're happy. you can't act cool during every interview. no should you try. your bad aspects (jealousy, hate) are never going away. we have intensely strong emotions. you can suppress some of them, but they don't just disappear.
* you're not fully in control of your actions. you may be taking actions based on some plan that you subconsciously have been cooking up for weeks. you might practice in your head but things go totally different in the moment. you don't actually have enough time to "think" on the spot (football). you have reactions like jumping out of freezing cold water. you have extremely powerful urgest which always come out one way or another. if you stick your finger in the "eat cake" dam, you might end up with a smoking habit. and you don't even control the details. do you control every detail of your fingers when you grab a cup of coffee? 
* you do have some control over these things. but it's often a long-term butterfly effect kind of control. if you want to quit alcohol, you can't do it by sheer willpower. you need to find something else to cling to. a distraction. a different angle.
- your emotions have inertia. they linger. they aren't "caused" by some event and then evaporate just like that. you can be sad just because of your body's natural cycles. like a boner in the night
- you are constantly telegraphing information and taking it in. you have body language, tone of voice, eye signals, gestures, facial expression. it's impossible to stop them. and you're always subconsciously taking in that information about other people and broadcasting it back. you may not consciously notice but some part of you always does.
- your deliberate perspective matters. your point of view has a huge impact on how you feel and what you do.
- your circumstances can make you go bonkers. you have needs that need to be met and traumas that need to be avoided. to some extent you can heal from / resist traumas if you get all your needs. but if you are impoverished in both ways, your normal operating functions start to break down. you can't think right, act right, learn right, communicate right, rub your tummy pat your head right.

- You are fundamentally Social. And fundamentally good
* You are capable of killing, stealing, torturing, and taking pleasure in the pain of others. but that's only a small part of you. your life circumstances, actions, point of view determine how big or small those are. what form they take. how often you feel them. whether you act on them and how.
* you are capable of kindness, altrusim, gentleness, beautiful self-expression. this is a larger part of you than the killing and torturing part. your actions, cirmustances, point of view affect what shape this takes
* humans are social creatures. during our millions of years of evolution, our tribes were our means for survival. we are exquisitely tuned to communicated, empathize, cooperate. we consider our family situation to be the root from which all our other needs (food, shelter, security) flow. so we consider bad or nonexistant close family relationships to mean that soon food and shelter will run out. we hate to be isolated. we hate to be ostracized. the worst thing that could possible happen? not lose your job. death of a loved one. when we are unhappy, the presence of an understanding friend changes everything. there's almost nothing we can't endure when we have another person with us. we think about love and friendship constantly. what's the most important websites? social media. what are all our songs about? love. all our movies? love. social interaction. what's the moral of every disney movie? you can have your money or success. but love and friendship are the real deal. would you run into a burning building to save anything but a person you love? or animal you love?

- people respond well to inevitability. we like to know the boundaries that we're working within
- people are good at not dealing with reality. we cling to one story or another. and we miss details that are right under our noses
- we are excellent at taking things out of context. we might yell at the child for disobedience. not realizing it's actually that we're freaked out about work or something
